spring:
  #1. mysql
  datasource:
    #    url: jdbc:mysql://10.68.7.127:33306/drelease?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://localhost:33060/test_create?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@123
    validationQuery: 'SELECT 1'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 设置默认使用Innodb引擎
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    enabled: true
    check-location: false
    locations: classpath:db/migration

logging:
  config: classpath:logback-console.xml
