CREATE TABLE `NewTable` (
`ID`  bigint(20) NOT NULL COMMENT '主键' ,
`COMPANY`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目所属企业' ,
`TYPE_NAME`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '类型名称' ,
`NAME`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目名称' ,
`GROUP`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目所属模块' ,
`GIT_NAMESPACE`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '代码在哪个namespace下' ,
`MARK`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目标识' ,
`DESCRIPTION`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目描述' ,
`TYPE`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目类型' ,
`PORTS`  varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目要监听的端口' ,
`ATTRIBUTE1`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位1' ,
`ATTRIBUTE2`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位2' ,
`ATTRIBUTE3`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位3' ,
`ATTRIBUTE4`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位4' ,
`ATTRIBUTE5`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位5' ,
`ATTRIBUTE6`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位6' ,
`ATTRIBUTE7`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位7' ,
`ATTRIBUTE8`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位8' ,
`ATTRIBUTE9`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位9' ,
`ATTRIBUTE10`  varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '扩展栏位10' ,
`ROW_VERSION`  bigint(20) NULL DEFAULT NULL COMMENT '行版本' ,
`IS_DELETED`  tinyint(1) NULL DEFAULT NULL COMMENT '是否已删除' ,
`CREATED_BY`  bigint(20) NOT NULL COMMENT '创建用户' ,
`CREATED_BY_NAME`  varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建用户名称' ,
`CREATION_TIME`  datetime NOT NULL COMMENT '创建时间' ,
`LAST_UPDATED_BY`  bigint(20) NULL DEFAULT NULL COMMENT '最后更新用户' ,
`LAST_UPDATED_BY_NAME`  varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '最后更新用户名称' ,
`LAST_UPDATE_TIME`  datetime NULL DEFAULT NULL COMMENT '最后更新时间' ,
PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci
COMMENT='项目表'
ROW_FORMAT=COMPACT
;